### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gao-hongfei123** [kchiama/DEM_PFC2D_models#2]
Hello, I am also engaged in ceramic research using pfc2d, but when I used the uniaxial compression experiment of pfc2d for strength check, I found that the elastic modulus could not reach more than 200gpa, so I would like to ask if you have been engaged in this research. In the future, I want to apply thermal coupling of temperature. In pfc, there is a thexp attribute for ball, but there is also a thexp attribute for thermalpipe. May I ask how to get the value?

**Comment by kchiama** [comment]
Hi Gao, 

Unfortunately I have not tested deep basement rocks using PFC yet, just near-surface sediment, so I am not sure how to navigate the issue with the 200 GPa. Perhaps Emma Finch or Amanda Hughes might know? They tend to work in large scale modeling and might have encountered this issue. I also have not worked in implementing thermal coupling but I am contemplating on how best to model the deformation of pipelines in near-surface earthquake ruptures. I didn't know there was a pipeline function built in to PFC directly and was considering building the pipeline out of much smaller balls with the correct properties to represent steel. 

Regarding your question on how to get the thexp attribute, I use FISH functions to output any values I need in PFC. For example, to get the ball positions, I use: 

> positions = ball.pos()
> fields = ['X','Y']
> rows = positions
> filename = "file.csv"
> with open(filename, 'w', newline='') as csvfile:
>       csvwriter = csv.writer(csvfile)
>       csvwriter .writerow(fields)
>       csvwriter .writerows(rows)

And the documentation for that can be found here: https://docs.itascacg.com/pfc700/pfc/pfcmodule/doc/manual/ball_manual/ball_fish/ball_intrinsics/fish_ball.pos.html?highlight=ba%20pos#function:ball.pos

I'm sorry I can't be more of a help, please feel free to email me at kchiama@g.harvard.edu!
